language: node_js
sudo: false
node_js:
- '5.0'
- 'stable'
branches:
  except:
  - /^v[0-9\.]+/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-1-12
  - EMBER_TRY_SCENARIO=ember-1-13
  - EMBER_TRY_SCENARIO=ember-2-0
  - EMBER_TRY_SCENARIO=ember-2-1
  - EMBER_TRY_SCENARIO=ember-2-2
  - EMBER_TRY_SCENARIO=ember-2-3
  - EMBER_TRY_SCENARIO=ember-2-4
  - EMBER_TRY_SCENARIO=ember-2-5
  - EMBER_TRY_SCENARIO=ember-2-6
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: RDPyQXdvFsgD5780P61DRJDDgANhaIsLhBGE6E2n82GdFHuQoEO9UCVLTUBGwDQsKo0UbNX6FAMnC+ijTRHyYUlqaUXW9N+xLPY300znQlT4eXQlNepuD33BpAugvguV4vXV+N7bsNZsBjhjcaImQtjd1Xg2ax3+LW5a/OpHTpubM7+Pb2l7W+AaFWjJjNeldjAeLit3yvTVZ0KVKuNChvC8IyjwOYa85YYPyND8Chs6TGyF9Cbl5PiIym26ocoJjcwaaykB48JiURU++wcGYKTEHsDzGtSmK1zvcLGEYoNgb5fl/2YFMEW1qyntQpNdh2JwGGNNgo77pPztcHKEM7oa+Wdjjvxb+yeBnP3/gxyNbNutQ892iKrR2ujOlZqkppnl2v7Y8LJKKjAjuLNLH3ugP7E/0F4P7jhwiEExVJCA27IVN6nH2nGebZOf+PyA9ntf3GGws6C1Rlx6fl+gnzNnFG77yvI/sGAKbBdt/UaMFSu+UcooAiQSdWwJEalxtzsuRqLV3okC7AIp0TTNVzTAMEGvMXLgZsmqZF8xeMIGaNIAwm1EuSRxoTdQ2HUKFwgLHgOMygEuXmxBsJGxgeJ1oSU8uEQ82I0asKk7J0MHVUlP1fx0dzXFYi9tdQMgKxuv0pdydQFFtoHci/9/znojFmFfWEmbI01m5sDWgAc=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-beta
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper
- pr-bumper check
install:
- npm install
- bower install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script:
- npm run lint
- ember try:one $EMBER_TRY_SCENARIO --- ember test
after_success:
- .travis/publish-coverage.sh
before_deploy:
- pr-bumper bump
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: LEO2MvvuuhkKi6hr0CyGdkAS1y6EL2B8ubj8uQMdYt3ni+XBnhJ6Q7Oif5PlAzY0gTK+p/MW5734vfLOlyKwA63pz4wrh4mncnaDKYQOMoRgcFagXNeARJycLM1aQMbnQ6idSG7dsunA2n7PyxOKC9ZdnJxnNYxjnkabwGf4KXGD6t0souvOqeuMevoe4F2DygNE4skh7tMwqDA2NTGyftCnz1mdfFaU6/FBeT7GKL2buV4cKReprJHBN1WT5RWy/KxS1YW2CiFaNg2cjdx7LPmFef7wFaLLyRyY6CcwqPP3dL8YCbql4zHrGST0K21sNEd2RLQ1iHXQnGmoKRBG3TIHqRD6am1a/TUy0ZnKmUeFLMtM7FnqNfj0QTC2+A3o9R+SirXFmAoJr1suPQZQUiCKXH+d1OQ1BmomQd8pynmdDtFlp04WWbEmtftTCkcONakpQP5cdjG1t0KU+QkuGzUXMT78G58S437iUtdukc3pGSYshZiA3zzf31D0N3T+6/QZbMwFl8yeBBSmC3t252s4IHejSt4rOg6tpXvppeD+jLv9mQX6GUKsR5RWtZzT+YcfXy2/ufZdxJ0YjTtRlJEP+jFEuAuhP9CjB2pwGA183Z2om1kqtoo0w7jp4uwCqn9J3HYwWVSr56grM9mUZPdv6JrE5a3/tq1jwDYpFAs=
  on:
    branch: master
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: false
notifications:
  slack:
    secure: REHG30SgCx0xdSyvsnCAp5tm3o9JIJYEHaJe18LEzSp5zYfnEPmb15eC29cVKA+2bv0QQtpWhKLPK8piAv4pbMC6D9kbogtjG6QrGyZMrA63QE3mmQGo9U9jTZtg+JkbCPKckIMpVI+UqexfW3BIxxjzWJjKNcKcih90ASgYhtGxxTqVPCZn/q6eskDHUjqgxitkAY3MnkydvII4pPWPM7wSP5PXd5saPOpxiI10AJnZDWwJMF/TSOA/ia/RyAT1d8EnaCyC6H+wDXVY55Sx760+I6o/nmtN6VR+cqJR4BjIxuk12f2DV8t2zJLKfqK7pKjWjPsRFy38bC4exe2a35d/KinAXESZIsnKp+ZoGw+8ysf8uplpmNePG06C0MVOodDLyOkYKmRVp3yq/IOhgc4gUODC8GikaJHf1BEMn1zBQPDKjRJkKZISJQHlohnpdO7hWSNG4ugX8iY1QkcBGGkdxgk4l2X/RK1H8cBpPHuuY/2kohWk7zg7Ovj2BJH8CoX/+OOipzvoo9tvsrEQgmRNy1FszueQijG5hS09DKZ1v2hjH41PxwBNiD06SsvhXSOBHMFVVdCO0hdqGWdxVe/Bk0U9HGUK9Qqg27ZiaEm+7dGhelecSvm61oRcokaYBTxuNxW6xDdOo+yAJonO/TvZs5mg+rpaWxp3McNSt2Q=
