---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-2.18.X
  - EMBER_TRY_SCENARIO=ember-3.1.X
  - EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

deploy:
  provider: npm
  email: admin@ember-redux.com
  skip_cleanup: true
  api_key:
    secure: fV+8F+kGluVt0DmvC8Sb84aL0jkvpexun7DJHqQDn2G+bjWhRFm6w8pu/PZfMsA5dW08Eize6GhgTmFo5ZsalmZlUCYqcIV62KpPcrL2cPBo4cmNDVuBsxv8/bLEQIaonx8tEzTCiRR2jtiZ3GsJh08Okb3grBh0rB1SfJZ2KdlcnAbIttKrp7uVXdZu8BK6FCvVbgt4mEeLSkqA3d30empVGr5CWkdRr3wzGiJiwn7prHdZeBUNIXKpkSOCE3ubj5wixmkQxGB3TmCqVSyYqAx9d8mOArzwDIAla2YIf5FXRv7N5eHmW127OWKGPrfghkfX9Mc+6PHWPMI/4v8HdB08ln1GZVCkkWdjTy6YVODBPew/pASHXlKNHIjS8QQ4FTbA6ViDDfAh0LzYUoUAkvidRaN1nWDE/sLvZjLJ0QdmXvNgg7JbTJ2/FpPrjkBwCxWBCQub96GR1uvrSh2QhUTGhHc2jtsPv66VbP1qifrPFYpphAxRjPBQYlKtzEi5RMpp3KAmsp31CrrCOTObN5LxWBG/e5UmJ+etvSHZunAc0SV0w8xGcPBvxwExJi/q8048b/Cg6XwkmukTCv3xAHCWXEUmxd8QFncttp90vYn3Erb1VMRx6392VjDmVeKnyxyL4BrRMh/FuTh940/D6QEYCGkCmIrTvBV2o29RFWY=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: true
